version: '3'

services:
  tensorflow-gpu:
    build:
      context: .
      dockerfile: Dockerfile
    image: speaker-impedance-tensorflow:latest
    container_name: speaker-impedance-tensorflow
    volumes:
      - .:/workspace
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    stdin_open: true
    tty: true 